SELECT CONTINENT 大陸名, NAME 国名, SURFACE_AREA 面積
FROM COUNTRY T1
WHERE 5 >= (
SELECT COUNT(*)
FROM COUNTRY T2
WHERE T1.CONTINENT = T2.CONTINENT
AND T2.SURFACE_AREA >= T1.SURFACE_AREA
)
ORDER BY CONTINENT, SURFACE_AREA DESC
;
