# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos"
  #config.vm.box = "https://github.com/holms/vagrant-centos7-box/releases/download/7.1.1503.001/CentOS-7.1.1503-x86_64-netboot.box"
  config.vm.hostname = "webserver"

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provision :shell, path: "provision.sh"

end
